// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcygWY83W5JxRHIQzuhfohN8TATPjEgmw',
    appId: '1:482449597040:web:2576c44208285c163f8ab5',
    messagingSenderId: '482449597040',
    projectId: 'miami-fit-app',
    authDomain: 'miami-fit-app.firebaseapp.com',
    storageBucket: 'miami-fit-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN2KLXyH3Ncj8dyjIaSokzpNUhnnI0bd0',
    appId: '1:482449597040:android:55ab504f4e7f14a33f8ab5',
    messagingSenderId: '482449597040',
    projectId: 'miami-fit-app',
    storageBucket: 'miami-fit-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMLpaXBnHoXkhhYmcZjlr58HluFtKl-gM',
    appId: '1:482449597040:ios:0389847f701c8fe33f8ab5',
    messagingSenderId: '482449597040',
    projectId: 'miami-fit-app',
    storageBucket: 'miami-fit-app.firebasestorage.app',
    iosBundleId: 'com.example.miamiFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMLpaXBnHoXkhhYmcZjlr58HluFtKl-gM',
    appId: '1:482449597040:ios:0389847f701c8fe33f8ab5',
    messagingSenderId: '482449597040',
    projectId: 'miami-fit-app',
    storageBucket: 'miami-fit-app.firebasestorage.app',
    iosBundleId: 'com.example.miamiFit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcygWY83W5JxRHIQzuhfohN8TATPjEgmw',
    appId: '1:482449597040:web:773102b43fe411923f8ab5',
    messagingSenderId: '482449597040',
    projectId: 'miami-fit-app',
    authDomain: 'miami-fit-app.firebaseapp.com',
    storageBucket: 'miami-fit-app.firebasestorage.app',
  );
}
